name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Встановлюємо Node.js >= 20
      - uses: actions/setup-node@v3
        with:
          node-version: 22

      # Встановлюємо залежності
      - run: npm ci

      # Збираємо фронт
      - run: npm run build

      # Деплой на Firebase
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: chatapp-b77bb
